general:
  root_path: crown_configs/func_test/
  enable_incomplete_verification: false
  device: cuda
  sparse_interm: true
  seed: 0
  verbose: false
model:
  name: Customized("model_def.py", "synthetic_model")
  input_shape:
  - 1
  - 100
specification:
  vnnlib_path: crown_configs/func_test/vnnlib/func_test_1.vnnlib
solver:
  batch_size: 32
  bound_prop_method: crown
bab:
  override_timeout: 180
  max_iterations: 50
  sort_domain_interval: 1
  branching:
    method: sb
    candidates: 3
    input_split:
      enable: true
      update_rhs_with_attack: true
      sb_coeff_thresh: 0.01
      softmax_temperature: 0.1
      ub_ratio: 0.75
attack:
  reject_bad: true
  pgd_order: skip
  pgd_early_stop: false
  pgd_lr_decay: 0.7
  pgd_lr_decay_mode: auto
  pgd_lr_target: 0.01
  pgd_auto_factor: 50
  input_split_check_adv:
    max_num_domains: 64
    pgd_steps: 25
    pgd_restarts: 128000
find_feasible_solution:
  enable: true
  save_solution: true
  show_solution: true
  report_per_iter: false
  save_solution_path: crown_configs/func_test/output/crown_sol.txt
  save_bab_path: crown_configs/func_test/output/crown_bab.pkl
  early_stop_patience: 200
  use_upper_bound: true
  warm_start: true
  preload_path: ANONYMOUS_DIR/box_pushing/crown_configs/pushing_T/output/crown_warmstart_18_11_32_5_0_10.pt
  pre_pgd_restarts: 1280000
  pre_pgd_steps: 5
  sample_with_solution: true
  bound_pgd_steps: 1
  bound_pgd_restarts: 100000
  bound_pgd_lr_decay: 0.5
  bound_pgd_auto_factor: 10
  bound_pgd_interval: 1
  bound_mppi_noise_factor: 0.1
  bound_mppi_weight_factor: 1
  reject_bad_in_bound: true
  fast_pass_bounding: false
  search_func: Customized("custom_attacker_sampling", "mppi_attack_with_general_specs")
  verbose: false
  mppi_config:
    n_steps: 8
    n_samples: 320000
    noise_factor: 0.3
    noise_decay: 0.7
    weight_factor: 0.5
    reject_bad: true
    early_stop: false
  cem_config:
    n_steps: 50
    n_samples: 320000
    jitter_factor: 1.0e-05
    elite_ratio: 1.0e-05
    min_n_elites: 5
    reject_bad: true
    early_stop: false
  pgd_config:
    n_steps: 20
    n_restarts: 80000
    early_stop: false
    lr_decay: 1
    lr_decay_mode: auto
    lr_target: 0.1
    restart_when_stuck: true
    reject_bad: false
