experiment_name: ''
wandb_id: 2
task_name: inserting
wandb: True
data_root: data/
seed: 0
model: MLP

data:
  state_dim: 18
  action_dim: 2
  obj_num: 2
  unit_size: 20
  hp_ratio: 0.8
  fix_hole: False
  pusher_size: 5
  num_episodes: 64000
  num_workers: 48
  episode_length: 25
  training: True
  saving: True
  visualizing: false
  gif: False
  scale: 100 # normalize the data, (x,y)/scale
  window_size: 500
  augment: False
  img_state: False
  img_size: 128
  enable_hnm: True
  weight_factor: 1 # weight the data in the loss function, exp(w*diff)
  weight_ub: 16 # exp(w*diff)<=weight_ub
  hn_th: 0.03 # pick error>=hn_th

real_exp:
  enable: False
  object_path_list: ['real_exp/object/hole.obj', 'real_exp/object/peg.obj']
  block_color_list: [[0,0,255],[255,255,0]]
  exp_id: 0
  overwrite: False
  sim_to_real_scale: 1000

train:
  include_com: false
  train_valid_ratio: 0.9
  architecture: [96, 192, 192, 96]
  n_history: 1
  n_rollout: 6
  n_rollout_valid: 6
  step_weight_ub: 2
  noise: 0.005 # std of the Gaussian noise to training data
  robust: false
  robust_settings:
    epsilon: 0.002
    alpha: 0.001
    iters: 3
  lr: 0.001
  lr_params:
    adam_beta1: 0.9
  lr_scheduler:
    type: "CosineAnnealingLR"
    enabled: True
  # lr_scheduler:
  #   type: "ReduceLROnPlateau"
  #   enabled: false
  #   factor: 0.3
  #   patience: 3
  #   threshold: 1.0e-4
  #   threshold_mode: 'rel'
  #   cooldown: 0
  #   min_lr: 0
  #   eps: 1e-08
  n_epoch_initial: 8
  batch_size: 256
  num_workers: 8
  lam_l1_reg: 0 # 2.0e-4 # l1 regularization
  use_ibp_loss: True
  lam_ibp_loss: 2.0e-5
  online_training:
    enable: False
    sample_data_per_epoch: 2 # every epoch, sample data 
    num_episodes: 3000

planning:
  plot_only: False
  horizon: 6
  n_act_step: 6 
  n_sim_step: 36
  num_test: 5
  open_loop: True
  action_bound: 0.3
  timeout: 90
  device: "cuda"
  reload: True
  method_types: ['MPPI', 'CROWN']
  # method_types: ['MPPI']
  # force_method_types: ['CROWN']
  force_method_types: []
  abcrown: crown_configs/inserting/planning.yaml
  abcrown_verbose: true # to get feasible solution in every iteration
  use_empirical_bounds: true
  enable_ub: true
  model: 'before'
  only_final_cost: True
  fixed_horizon: false
  use_prev_sol: false
  warm_start_from_sampling: true
  cost_norm: 1 # 1 or 2
  mppi:
    n_sample: 200000
    n_update_iter: 50
    reward_weight: 20
    noise_level: 'auto'
  model_path: None

visualize:
  exp_dir: "closed_loop_planning_6_30"

training: True # if not training, will disable Gumbel
log:
  log_per_iter: 5
