experiment_name: ''
wandb_id: 3
task_name: merging_L
wandb: True
debug: False
data_root: data/
seed: 0
model: MLP

data:
  state_dim: 12
  action_dim: 2
  obj_num: 2
  unit_size: 28
  leg_shape: [1,1]
  foot_shape: [3,1]
  pusher_size: 5
  num_episodes: 64000
  num_workers: 48
  episode_length: 40
  episode_shift: 5
  training: True
  saving: True
  visualizing: False
  gif: False
  scale: 100 # normalize the data, (x,y)/scale
  window_size: 500
  augment: False
  img_state: False
  img_size: 128
  enable_hnm: True
  weight_factor: 1 # weight the data in the loss function, exp(w*diff)
  weight_ub: 16 # exp(w*diff)<=weight_ub
  hn_th: 0.03 # pick error>=hn_th

real_exp:
  enable: False
  object_path_list: ['real_exp_new/object/l.obj', 'real_exp_new/object/l.obj']
  # with two lights on: orange:[0.91,0.4,0.25] pink:[0.6,0.3, 0.4] green:[0.51, 0.62, 0.51], purple:[0.47,0.49,0.61]
  block_color_list: [[0.91,0.4,0.25], [0.51, 0.62, 0.51]] # tiezhi:[[0,0.22,0.35],[0.80, 0.35, 0.15]]
  exp_id: 0
  overwrite: False
  sim_to_real_scale: 1000
  time_limit: 30

train:
  include_com: false
  train_valid_ratio: 0.90
  architecture: [128, 256, 256, 128]
  n_history: 1
  n_rollout: 6
  n_rollout_valid: 6
  step_weight_ub: 2
  noise: 0.005 # std of the Gaussian noise to training data
  robust: false
  robust_settings:
    epsilon: 0.002
    alpha: 0.001
    iters: 3
  lr: 0.001
  lr_params:
    adam_beta1: 0.9
  lr_scheduler:
    type: "CosineAnnealingLR"
    enabled: True
  # lr_scheduler:
  #   type: "ReduceLROnPlateau"
  #   enabled: false
  #   factor: 0.3
  #   patience: 3
  #   threshold: 1.0e-4
  #   threshold_mode: 'rel'
  #   cooldown: 0
  #   min_lr: 0
  #   eps: 1e-08
  n_epoch_initial: 6
  batch_size: 256
  num_workers: 8
  lam_l1_reg: 0 # 2.0e-4 # l1 regularization
  use_ibp_loss: True
  lam_ibp_loss: 2.0e-5
  shape_loss: 0.1
  online_training:
    enable: False
    sample_data_per_epoch: 2 # every epoch, sample data 
    num_episodes: 3000

planning:
  plot_only: False
  horizon: 10
  n_act_step: 6 # number of steps to act after each planning call
  n_sim_step: 36
  num_test: 5
  open_loop: False
  action_bound: 0.3
  timeout: 600
  device: "cuda"
  reload: True
  method_types: ['MPPI', 'CROWN']
  # method_types: ['CROWN']
  # force_method_types: ['CROWN']
  force_method_types: []
  abcrown: crown_configs/merging_L/planning.yaml
  abcrown_verbose: true # to get feasible solution in every iteration
  use_empirical_bounds: true
  enable_ub: true
  model: 'before'
  only_final_cost: True
  fixed_horizon: false
  use_prev_sol: false
  warm_start_from_sampling: true
  warm_start_method: 'CEM'
  cost_norm: 1 # 1 or 2
  penalty_type: 0 # 0: no penalty, 1: penalty on pusher, 2: penalty on object, 3: penalty on both
  obs_pos_list: [[2.5,2.5]]
  obs_size_list: [0.1]
  obs_type: 'circle'
  obs_enlarge: 0.1 # enlarge the obstacle in long-horizon planning
  exchange_obj: false
  mppi:
    n_sample: 50000
    n_update_iter: 5
    reward_weight: 50
    noise_level: 'auto'
    noise_type: 'normal'
  cem:
    n_sample: 50000
    n_update_iter: 8
    jitter_factor: 0.001
    elite_ratio: 0.00001
    min_n_elites: 10
    # decentCEM
    n_agents: 10
  gd:
    n_sample: 50000
    n_update_iter: 8
    lr: 0.001
    noise_type: 'random'
    n_restart_round: 2
  model_path: None
  predefined_planning_path: None
  hierarchical: 
    enable: True
    horizon: 5
    n_act_step: 1
    only_final_cost: True
    refer_pos: false
    action_bound: 0.2
    # mppi settings
    n_sample: 200000
    n_update_iter: 15
    reward_weight: 50
    noise_level: 0.04
    subgoal_interval: 2
    num_subgoal: 8
    buffer_round: 0
    reach_threshold: 0.1 # 0.4


visualize:
  exp_dir: "closed_loop_planning_6_30"

training: True # if not training, will disable Gumbel
log:
  log_per_iter: 5