general:
  root_path: /home/keyi/ICLR_release_local/crown_configs/pushing_T/
  enable_incomplete_verification: false
  device: cuda
  sparse_interm: true
  seed: 0
  verbose: false
model:
  name: 'Customized("wrapped_model.py", "wrapped_model", model_path="ckpts/pushing_T/dynamics_model.pth",
    model_config={''enable_latent'': False, ''state_dim'': 8, ''action_dim'': 2, ''n_history'':
    1, ''horizon'': 20, ''cost_norm'': 1, ''only_final_cost'': True, ''device'': ''cuda'',
    ''obs_pos_list'': [[1.1, 2.5], [3.05, 2.75]], ''obs_size_list'': [0.3, 0.3], ''obs_type'':
    ''circle'', ''obs_enlarge'': 0.4, ''penalty_type'': 3})'
  input_shape:
  - 1
  - 40
specification:
  vnnlib_path: vnnlib/_9_3_37_11.vnnlib
solver:
  batch_size: 16
  bound_prop_method: crown
bab:
  override_timeout: 60
  max_iterations: 12
  sort_domain_interval: 1
  branching:
    method: sb
    candidates: 3
    input_split:
      enable: true
      update_rhs_with_attack: true
      sb_coeff_thresh: 0.01
      softmax_temperature: 0.05
      branching_heuristic: Customized("custom_branching_heuristics", "customized_input_split_branching")
      ub_ratio: 0.75
attack:
  reject_bad: true
  pgd_order: skip
  pgd_early_stop: false
  pgd_lr_decay: 1
  pgd_lr_decay_mode: auto
  pgd_lr_target: 0.01
  pgd_auto_factor: 50
  input_split_check_adv:
    max_num_domains: 32
    pgd_steps: 15
    pgd_restarts: 110000
find_feasible_solution:
  enable: true
  save_solution: true
  show_solution: true
  report_per_iter: false
  report_time: true
  save_solution_path: /home/keyi/ICLR_release_local/crown_configs/pushing_T/output/crown_sol_9_3_37_11.txt
  save_bab_path: /home/keyi/ICLR_release_local/crown_configs/pushing_T/output/crown_bab_9_3_37_11.pkl
  early_stop_patience: 200
  use_upper_bound: true
  warm_start: true
  preload_path: /home/keyi/ICLR_release_local/crown_configs/pushing_T/output/crown_warmstart_9_3_37_11.pt
  pre_pgd_restarts: 200000
  pre_pgd_steps: 1
  sample_with_solution: true
  bound_pgd_steps: 1
  bound_pgd_restarts: 100000
  bound_pgd_lr_decay: 0.5
  bound_pgd_auto_factor: 10
  bound_pgd_interval: 1
  bound_mppi_noise_factor: 0.1
  bound_mppi_weight_factor: 1
  reject_bad_in_bound: true
  fast_pass_bounding: true
  final_ibp_bounding: true
  record_distribution_for_branching: true
  elite_ratio_for_branching: 0.01
  min_n_elites_for_branching: 10
  early_stop_bounding:
    conditioner: Customized("custom_early_stop_condition_in_bounding", "customized_early_stop_conditioner",
      max_relu_nodes=8, max_prop_nodes=6)
    retry_patience: 10
  search_func: Customized("custom_attacker_sampling", "cem_attack_with_general_specs")
  verbose: false
  mppi_config:
    n_steps: 8
    n_samples: 320000
    noise_factor: 0.15
    noise_decay: 0.96
    weight_factor: 0.001
    reject_bad: true
    early_stop: false
  cem_config:
    n_steps: 50
    n_samples: 320000
    jitter_factor: 0.0001
    elite_ratio: 0.0001
    min_n_elites: 10
    reject_bad: true
    early_stop: false
  pgd_config:
    n_steps: 20
    n_restarts: 80000
    early_stop: false
    lr_decay: 1
    lr_decay_mode: auto
    lr_target: 0.1
    restart_when_stuck: true
    reject_bad: false
